# https://aka.ms/yaml
jobs:
- job: 'Windows'
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python36_Node10:
        python.version: '3.6'
        python.architecture: 'x64'
        node_version: 10.x
      Python37_Node12:
        python.version: '3.7'
        python.architecture: 'x64'
        node_version: 12.x
      Python38_Node13:
        python.version: '3.8'
        python.architecture: 'x64'
        node_version: 13.x
    maxParallel: 6

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

# change this to make ci after addressing git CRLF issue
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'make all'

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python27_Node8:
        python.version: '2.7'
        node_version: 8.x
      Python35_Node10:
        python.version: '3.5'
        node_version: 10.x
      Python37_Node12:
        python.version: '3.7'
        node_version: 12.x
      Python38_Node13:
        python.version: '3.8'
        node_version: 13.x
    maxParallel: 6

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'make ci'

- job: 'MacOS'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python27_Node8:
        python.version: '2.7'
        node_version: 8.x
      Python37_Node12:
        python.version: '3.7'
        node_version: 12.x
    maxParallel: 6

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'make ci'

